"""Minimal QFTX gRPC client.

Prereqs:
    pip install grpcio grpcio-tools
    python -m grpc_tools.protoc \
        -I ../../proto --python_out=. --grpc_python_out=. \
        ../../proto/trading.proto

Then:
    python grpc-client.py
"""

import grpc

# Generated by protoc — names are trading_pb2 / trading_pb2_grpc.
import trading_pb2 as pb
import trading_pb2_grpc as svc

PRICE_SCALE = 100_000_000
STATUS_NAME = {
    pb.NEW: "New",
    pb.PARTIALLY_FILLED: "PartiallyFilled",
    pb.FILLED: "Filled",
    pb.CANCELLED: "Cancelled",
    pb.REJECTED: "Rejected",
}


def main():
    with grpc.insecure_channel("127.0.0.1:9001") as ch:
        client = svc.TradingServiceStub(ch)

        # 1) Place a resting buy 5 @ 100 via unary RPC.
        resp = client.PlaceOrder(pb.PlaceOrderRequest(order=pb.NewOrder(
            order_id=1, symbol_id=0,
            side=pb.BUY, ord_type=pb.LIMIT, tif=pb.DAY,
            price=100 * PRICE_SCALE, qty=5, client_id=1,
        )))
        for r in resp.reports:
            print(
                f"PlaceOrder report: status={STATUS_NAME[r.status]} "
                f"last_qty={r.last_qty} leaves_qty={r.leaves_qty}"
            )

        # 2) Cancel it.
        cancel = client.CancelOrder(pb.CancelOrderRequest(cancel=pb.CancelOrder(
            order_id=1, symbol_id=0,
        )))
        r = cancel.report
        print(f"Cancel report:    status={STATUS_NAME[r.status]} order_id={r.order_id}")


if __name__ == "__main__":
    main()
